# time podman build -t imagem-deploy-os -f Containerfile ../target

FROM eclipse-temurin:21-jre-alpine

COPY quarkus-app/lib/ /deployments/lib/
COPY quarkus-app/quarkus-run.jar /deployments/app.jar
COPY quarkus-app/app/ /deployments/app/
COPY quarkus-app/quarkus/ /deployments/quarkus/

CMD ["java", "-jar", "/deployments/app.jar"]